message: Greetings from the PRODUCT-COMMAND-SIDE microservice [using the LOCALHOST config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        queue: product.default.queue
        databaseName: products
        eventsCollectionName: events
        snapshotCollectionName: snapshots
        sagaCollectionName: sagas
#    datasource:
#        url: jdbc:oracle:thin:system/oracle@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=xe)))
#    jpa:
#      #generate-ddl: true
#      hibernate:
#        ddl-auto: create
#        show_sql: true
datasource:
  url: jdbc:oracle:thin:system/oracle@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=xe)))
  username: system
  password: oracle
  driver-class-name: oracle.jdbc.OracleDriver
  transactionTimeout: 5 #Seconds
  connectionPool:
     initialPoolSize: 20
     maxPoolSize: 20
     minPoolSize: 20
     maxStatements: 50
     checkoutTimeout: 30000 # Milliseconds
  properties:
     hibernate.dialect: 'org.hibernate.dialect.Oracle10gDialect'
     hibernate.naming_strategy: 'org.hibernate.cfg.DefaultComponentSafeNamingStrategy'
     hibernate.hbm2ddl.auto: create-drop
     #hibernate.show_sql: true
     #hibernate.format_sql: true
     hibernate.cache.use_second_level_cache: false
     hibernate.cache.use_query_cache: false
     hibernate.generate_statistics: false

logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.pankesh: INFO
    file: ./build/logs/command-side-server.log