message: Greetings from the PRODUCT-COMMAND-SIDE microservice [using the LOCALHOST config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: product.events.fanout.exchange
        queue: product.default.queue
        databaseName: products
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://localhost:27017/products
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.pankesh: INFO
    file: ./build/logs/command-side-server.log