message: Greetings from the PRODUCT-QUERY-SIDE microservice [using the LOCALHOST config].

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: product.events.fanout.exchange
        queue: event.stream
        terminal: product.axon.terminal
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    data:
        rest:
            #base-path: api/v1
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.pankesh: DEBUG
    file: ./build/logs/query-side-server.log