version: '2'
services:
  config:
    image: pankesh/config-service
    container_name: config
    ports:
     - "8888:8888"
    volumes:
     - ..:/home/ben/src/github
    depends_on:
     - mongodb
     - rabbitmq
  discovery:
    image: pankesh/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  gateway:
    image: pankesh/gateway-service
    container_name: gateway
    ports:
     - "8080:8080"
    depends_on:
     - config
     - discovery