version: '2'
services:
  config:
    image: pankesh/config-service
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  discovery:
    image: pankesh/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  gateway:
    image: pankesh/gateway-service
    container_name: gateway
    ports:
     - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - discovery
     - config
  product-command-side:
    image: pankesh/product-command-side:latest
    container_name: product-cmd-side
    depends_on:

     - discovery
     - config
    ports:
      - "9000"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  product-query-side:
    image: pankesh/product-query-side:latest
    container_name: product-qry-side
    depends_on:

     - discovery
     - config
    ports:
     - "9001"
    environment:
     - SPRING_PROFILES_ACTIVE=production